### ISSUE TITLE
Can't run the "npm run server" because of babel error

### ISSUE THREAD

**Issue by sodacrackers** [olegsmetanin/react_react-router_flummox_example#4]
Apologies if I'm posting in the wrong spot.  
Had to upgrade node dependencies and the package.json.  This was helpful:  https://www.npmjs.com/package/npm-check-updates

Currently having an issue with Babel and building.  Any ideas about an **unsupported option** or how to run with a local server?  

```
> babel-node --experimental server/server.js


  error: unknown option --experimental 
```

``````
C:\www\www repos\react_react-router_flummox_example>npm run server
.....

npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli
.js" "run" "server"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! react_react-router_flummox_browserify_example@0.0.1 server: `babel-node --experimental server/server.js`
npm ERR! Exit status 1```


``````

**Comment by olegsmetanin** [comment]
Try now https://github.com/olegsmetanin/react_react-router_flummox_example/commit/b2c3d85863b71a38641d86ff6ecf45cde1837e18
